# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67524752db693c94f7be752fd784dbb4999e16cb7dff533bbb409bb9d2723b2e235851b4d87c299b8ddc8f37364a72dd80f7fafb4944751122607b4fc615b37f

test:
  secret_key_base: c70345fa84400010eeb006c664a21e6085cf0b01200c4be1a41275f1eddbc6da84975fde72ea415b07fabb7c38395f3cfaaf7ae98496af277264ef40ab70b4fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
